# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171124_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approved_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
