# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171125_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
