# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20171125_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='profile_pictures/male.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
