# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180108_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest_shown',
            field=models.ManyToManyField(related_name='_profile_interest_shown_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(related_name='_profile_matches_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
    ]
