# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 18:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20180221_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 2, 10, 18, 41, 24, 587911)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest_shown',
            field=models.ManyToManyField(related_name='interest_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(related_name='matches_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
