# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20180223_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 2, 11, 5, 7, 42, 2861)),
        ),
    ]
